package com.therian.oc.aaa.ui.cosplay

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.text.Html
import android.view.LayoutInflater
import android.view.View
import android.view.WindowManager
import androidx.activity.viewModels
import androidx.core.graphics.createBitmap
import androidx.lifecycle.lifecycleScope
import com.bumptech.glide.Glide
import com.therian.oc.aaa.R
import com.therian.oc.aaa.core.base.BaseActivity
import com.therian.oc.aaa.core.extensions.checkInternet
import com.therian.oc.aaa.core.extensions.gone
import com.therian.oc.aaa.core.extensions.handleBackLeftToRight
import com.therian.oc.aaa.core.extensions.hideNavigation
import com.therian.oc.aaa.core.extensions.select
import com.therian.oc.aaa.core.extensions.showInterAll
import com.therian.oc.aaa.core.extensions.startIntentRightToLeft
import com.therian.oc.aaa.core.extensions.tap
import com.therian.oc.aaa.core.extensions.visible
import com.therian.oc.aaa.core.helper.InternetHelper
import com.therian.oc.aaa.core.helper.MediaHelper
import com.therian.oc.aaa.core.utils.key.IntentKey
import com.therian.oc.aaa.core.utils.key.ValueKey
import com.therian.oc.aaa.core.utils.state.SaveState
import com.therian.oc.aaa.data.model.custom.CustomizeModel
import com.therian.oc.aaa.data.model.custom.NavigationModel
import com.therian.oc.aaa.data.model.custom.SuggestionModel
import com.therian.oc.aaa.databinding.ActivityCosplayRandomBinding
import com.therian.oc.aaa.dialog.YesNoDialog
import com.therian.oc.aaa.ui.customize.CustomizeCharacterViewModel
import com.therian.oc.aaa.ui.home.DataViewModel
import com.lvt.ads.util.Admob
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class CosplayRandomActivity : BaseActivity<ActivityCosplayRandomBinding>() {

    private val dataViewModel: DataViewModel by viewModels()
    private val customizeViewModel: CustomizeCharacterViewModel by viewModels()
    private var currentSuggestion: SuggestionModel? = null
    private var hasAutoGenerated = false

    override fun setViewBinding(): ActivityCosplayRandomBinding {
        return ActivityCosplayRandomBinding.inflate(LayoutInflater.from(this))
    }

    override fun initView() {
        lifecycleScope.launch { showLoading() }
        dataViewModel.ensureData(this)
        binding.titleGuide.select()
        setCosPlayButtonEnabled(false)
        binding.tvCosplay.isSelected = true
        binding.tvRandom.isSelected = true
        binding.bgFrame.text =
            Html.fromHtml(getString(R.string.guide_cosplay), Html.FROM_HTML_MODE_COMPACT)
    }

    override fun dataObservable() {
        lifecycleScope.launch {
            dataViewModel.allData.collect { data ->
                if (data.isNotEmpty() && !hasAutoGenerated) {
                    hasAutoGenerated = true
                    handleGenerate()
                }
            }
        }
    }

    override fun viewListener() {
        binding.apply {
            btnGenerate.tap(800) { checkInternet { handleGenerate() } }
            btnCosPlay.tap(800) {
                checkInternet {
                    customizeViewModel.checkDataInternet(this@CosplayRandomActivity) { handlePlay() }
                }
            }
            actionBar.btnActionBarLeft.tap { showInterAll {  handleBackLeftToRight() }}
            actionBar.btnActionBarRight.tap {
                vOverlayGuide.visible()
                containerGuide.visible()
            }
            btnCloseGuide.tap {
                containerGuide.gone()
                vOverlayGuide.gone()
            }
        }
    }

    override fun initActionBar() {
        binding.actionBar.apply {
            btnActionBarLeft.visible()
            btnActionBarRight.setImageResource(R.drawable.ic_guide)
            btnActionBarRight.visible()
            tvCenter.setText(R.string.cosplay)
            tvCenter.visible()
        }
    }

    private fun handleGenerate() {
        val allData = dataViewModel.allData.value
        if (allData.isEmpty()) return
        val hasInternet = InternetHelper.isInternetAvailable(this)
        if (!hasInternet) {
            lifecycleScope.launch { dismissLoading() }
            showNoInternetDialog()
            return
        }
        val randomData = allData.random()
        generateRandomSuggestion(randomData)
    }

    private fun showNoInternetDialog() {
        val dialog = YesNoDialog(
            this,
            R.string.no_internet,
            R.string.please_check_your_internet,
            isError = true
        )
        dialog.show()
        dialog.onYesClick = {
            dialog.dismiss()
            hideNavigation()
        }
    }

    private fun generateRandomSuggestion(summary: CustomizeModel) {
        val exHandler = CoroutineExceptionHandler { _, _ -> }
        CoroutineScope(SupervisorJob() + Dispatchers.IO + exHandler).launch {
            try {
                withContext(Dispatchers.Main) { showLoading() }

                val data = dataViewModel.getCharacter(
                    this@CosplayRandomActivity,
                    summary
                ) ?: run {
                    withContext(Dispatchers.Main) { dismissLoading() }
                    return@launch
                }
                customizeViewModel.positionSelected =
                    dataViewModel.allData.value.indexOf(summary)
                customizeViewModel.setDataCustomize(data)
                customizeViewModel.updateAvatarPath(data.avatar)
                customizeViewModel.resetDataList()
                customizeViewModel.addValueToItemNavList()
                customizeViewModel.setItemColorDefault()
                val allNavList = data.layerList.mapIndexed { index, layer ->
                    NavigationModel(
                        imageNavigation = layer.imageNavigation,
                        layerIndex = index
                    )
                }.toCollection(ArrayList())
                allNavList.firstOrNull()?.isSelected = true
                customizeViewModel.setBottomNavigationList(allNavList)
                customizeViewModel.setClickRandomFullLayer()

                val suggestion = customizeViewModel.getSuggestionList()
                currentSuggestion = suggestion

                val paths = suggestion.pathSelectedList.filter { it.isNotEmpty() }

                if (paths.isEmpty()) {
                    withContext(Dispatchers.Main) { dismissLoading() }
                    return@launch
                }

                val firstBitmap = loadLayerWithRetry(paths.first())
                val w = (firstBitmap.width / 2).coerceAtLeast(1)
                val h = (firstBitmap.height / 2).coerceAtLeast(1)

                val bitmaps = coroutineScope {
                    paths.map { path ->
                        async {
                            loadLayerWithRetry(path, w, h)
                        }
                    }.awaitAll()
                }

                val combined = createBitmap(w, h)
                val canvas = Canvas(combined)
                bitmaps.forEach { bmp ->
                    canvas.drawBitmap(bmp, (w - bmp.width) / 2f, (h - bmp.height) / 2f, null)
                }

                MediaHelper.saveBitmapToPreviewCache(
                    this@CosplayRandomActivity, combined
                ).collect { state ->
                    if (state is SaveState.Success) {
                        suggestion.pathInternalRandom = state.path
                        withContext(Dispatchers.Main) {
                            binding.imvImage.visibility = View.VISIBLE
                            binding.guidRandom.gone()
                            Glide.with(this@CosplayRandomActivity)
                                .load(state.path).into(binding.imvImage)
                            setCosPlayButtonEnabled(true)
                            dismissLoading()
                        }
                    }
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    dismissLoading()
                    showNoInternetDialog()
                }
            }
        }
    }

    private suspend fun loadLayerWithRetry(
        path: String,
        width: Int? = null,
        height: Int? = null
    ): Bitmap {
        var lastError: Exception? = null

        repeat(MAX_LAYER_LOAD_ATTEMPTS) { attempt ->
            try {
                val request = Glide.with(this@CosplayRandomActivity)
                    .asBitmap()
                    .load(path)
                return if (width != null && height != null) {
                    request.submit(width, height).get()
                } else {
                    request.submit().get()
                }
            } catch (exception: CancellationException) {
                throw exception
            } catch (exception: Exception) {
                lastError = exception
                android.util.Log.w(
                    "CosplayRandom",
                    "Layer load failed ${attempt + 1}/$MAX_LAYER_LOAD_ATTEMPTS " +
                        "path='$path' size=${width ?: "original"}x${height ?: "original"}",
                    exception
                )
                if (attempt < MAX_LAYER_LOAD_ATTEMPTS - 1) {
                    delay(RETRY_DELAY_MS * (attempt + 1))
                }
            }
        }

        throw lastError ?: IllegalStateException("Unable to load layer: $path")
    }

    private fun setCosPlayButtonEnabled(enabled: Boolean) {
        binding.btnCosPlay.isEnabled = enabled
        binding.btnCosPlay.alpha = if (enabled) 1f else 0.4f
    }

    companion object {
        private const val MAX_LAYER_LOAD_ATTEMPTS = 3
        private const val RETRY_DELAY_MS = 400L
    }

    private fun handlePlay() {
        val suggestion = currentSuggestion ?: return
        lifecycleScope.launch {
            showLoading()
            withContext(Dispatchers.IO) {
                MediaHelper.writeModelToFile(
                    this@CosplayRandomActivity,
                    ValueKey.SUGGESTION_FILE_INTERNAL,
                    suggestion
                )
            }
            dismissLoading()
            showInterAll {
                startIntentRightToLeft(
                    CosplayCustomizeActivity::class.java,
                    IntentKey.COSPLAY_CHARACTER_POSITION_KEY,
                    customizeViewModel.positionSelected
                )
            }
        }
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        if (hasFocus) {
            applyUiCustomize()
            hideNavigation()
            window.decorView.removeCallbacks(reHideRunnable)
            window.decorView.postDelayed(reHideRunnable, 1500)
        } else {
            window.decorView.removeCallbacks(reHideRunnable)
        }
    }

    private val reHideRunnable = Runnable {
        applyUiCustomize()
        hideNavigation()
    }

    @Suppress("DEPRECATION")
    private fun applyUiCustomize() {
        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
        window.statusBarColor = Color.TRANSPARENT
        window.navigationBarColor = Color.TRANSPARENT
        window.decorView.systemUiVisibility =
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                    View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                    View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
                    View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                    View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
    }



    fun initNativeCollab() {
//        Admob.getInstance().loadNativeCollapNotBanner(
//            this,
//            getString(R.string.native_cl_cosplay),
//            binding.flNativeCollab
//        )
    }

    override fun initAds() {
//        initNativeCollab()
    }

    override fun onRestart() {
        super.onRestart()
//        initNativeCollab()
    }

}
